#!/usr/bin/env bash

set -o errexit
set -o pipefail

SCRIPT_DIR="$1"
SCRIPT_FILE="$SCRIPT_DIR/$2"
DATE=$(date +%D)

if [[ $# == 0 ]]; then
	echo Please provide a script dir/name
	exit
fi

if [[ $# -ne 2 ]]; then
	readonly SCRIPT_DIR="."
	readonly SCRIPT_FILE="$SCRIPT_DIR/$1"
fi

if [[ $SCRIPT_FILE == *.sh ]]; then
	readonly COMMENT_SYMBOL="#"
	readonly LANG_LOCATION="!/usr/bin/env bash"
elif [[ $SCRIPT_FILE == *.py ]]; then
	readonly COMMENT_SYMBOL="#"
	readonly LANG_LOCATION="!/usr/bin/python"
else
	echo File type not recognised, Assuming Bash Script setting Comment Symbol to "#"
	readonly COMMENT_SYMBOL="#"
	readonly LANG_LOCATION="!/usr/bin/env bash"
fi

if [[ -f "$SCRIPT_FILE" ]]; then
	echo $SCRIPT_FILE exists.
	echo Opening it anyway with no appends
	vim $SCRIPT_FILE
else
	touch $SCRIPT_FILE
	chmod +x $SCRIPT_FILE
	echo Script Created
	echo $COMMENT_SYMBOL$LANG_LOCATION >> $SCRIPT_FILE
	echo $COMMENT_SYMBOL AHMZA >> $SCRIPT_FILE
	echo $COMMENT_SYMBOL $DATE >> $SCRIPT_FILE
	echo $COMMENT_SYMBOL This script ... >> $SCRIPT_FILE
	vim $SCRIPT_FILE
fi

exit
